name: test-core-smb-on

on: 
    workflow_dispatch:
    push:
    pull_request:
      branches: [ main ]

jobs:
  test-core-smb-on-amd64:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    uses: ./.github/workflows/run-core-tests-smb-on.yaml
    with:
      WORKFLOW_AGENT: ubuntu-latest
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

  test-core-smb-on-arm64:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    uses: ./.github/workflows/run-core-tests-smb-on.yaml
    with:
      WORKFLOW_AGENT: spacesdk-ubuntu-2204LTS-arm64
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}